spring:
  #数据源
  datasource:
    url: jdbc:mysql:///springboot?useUnicode=true&allowMultiQueries=true&rewriteBatchedStatements=true&characterEncoding=utf-8&useSSL=false&useServerPrepStmts=false
    username: root
    password: 12345678
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
