spring:
  datasource:
    url: jdbc:mysql:///spring_cache
    password: 12345678
    username: root
  redis:
    host: 127.0.0.1
    port: 6379
logging:
  level:
    top.aftery.mapper: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
